DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS bans;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS replies;
DROP TABLE IF EXISTS threads;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS users;
