// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bans.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBan = `-- name: CreateBan :one
INSERT INTO bans (user_id, ip, reason, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, ip, reason, expires_at, created_at
`

type CreateBanParams struct {
	UserID    pgtype.UUID
	Ip        *netip.Addr
	Reason    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateBan(ctx context.Context, arg CreateBanParams) (Ban, error) {
	row := q.db.QueryRow(ctx, createBan,
		arg.UserID,
		arg.Ip,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i Ban
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ip,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveBanForIP = `-- name: GetActiveBanForIP :one
SELECT id, user_id, ip, reason, expires_at, created_at
FROM bans
WHERE ip = $1
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveBanForIP(ctx context.Context, ip *netip.Addr) (Ban, error) {
	row := q.db.QueryRow(ctx, getActiveBanForIP, ip)
	var i Ban
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ip,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveBanForUser = `-- name: GetActiveBanForUser :one
SELECT id, user_id, ip, reason, expires_at, created_at
FROM bans
WHERE user_id = $1
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveBanForUser(ctx context.Context, userID pgtype.UUID) (Ban, error) {
	row := q.db.QueryRow(ctx, getActiveBanForUser, userID)
	var i Ban
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ip,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveBans = `-- name: ListActiveBans :many
SELECT id, user_id, ip, reason, expires_at, created_at
FROM bans
WHERE expires_at IS NULL OR expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveBans(ctx context.Context) ([]Ban, error) {
	rows, err := q.db.Query(ctx, listActiveBans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ban
	for rows.Next() {
		var i Ban
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Ip,
			&i.Reason,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
