// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Ban struct {
	ID        string
	UserID    pgtype.UUID
	Ip        *netip.Addr
	Reason    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt time.Time
}

type Board struct {
	ID          string
	Slug        string
	Name        string
	Description string
	CreatedAt   time.Time
}

type RefreshToken struct {
	ID         string
	UserID     string
	FamilyID   string
	TokenHash  string
	Revoked    bool
	ReplacedBy pgtype.UUID
	ExpiresAt  time.Time
	CreatedAt  time.Time
}

type Reply struct {
	ID        string
	ThreadID  string
	UserID    string
	Body      string
	ImageUrl  pgtype.Text
	ReplyToID pgtype.UUID
	CreatedAt time.Time
}

type Report struct {
	ID         string
	TargetType string
	TargetID   string
	ReporterID string
	Reason     string
	Status     string
	CreatedAt  time.Time
}

type Thread struct {
	ID        string
	BoardID   string
	UserID    string
	Title     string
	Body      string
	ImageUrl  pgtype.Text
	IsPinned  bool
	IsLocked  bool
	BumpedAt  time.Time
	CreatedAt time.Time
}

type User struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	AvatarUrl    pgtype.Text
	Bio          string
	Role         string
	CreatedAt    time.Time
	Color        string
}
