// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBan(ctx context.Context, arg CreateBanParams) (Ban, error)
	CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateReply(ctx context.Context, arg CreateReplyParams) (CreateReplyRow, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteReply(ctx context.Context, id string) error
	DeleteThread(ctx context.Context, id string) error
	GetActiveBanForIP(ctx context.Context, ip *netip.Addr) (Ban, error)
	GetActiveBanForUser(ctx context.Context, userID pgtype.UUID) (Ban, error)
	GetActiveTokenByFamily(ctx context.Context, familyID string) (RefreshToken, error)
	GetBoardBySlug(ctx context.Context, slug string) (Board, error)
	GetBoardThreadCount(ctx context.Context, boardID string) (int64, error)
	GetBoardThreads(ctx context.Context, arg GetBoardThreadsParams) ([]GetBoardThreadsRow, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetReplyByID(ctx context.Context, id string) (Reply, error)
	GetReportByID(ctx context.Context, id string) (Report, error)
	GetThreadBoardID(ctx context.Context, id string) (string, error)
	GetThreadByID(ctx context.Context, id string) (GetThreadByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPublicByUsername(ctx context.Context, username string) (GetUserPublicByUsernameRow, error)
	ListActiveBans(ctx context.Context) ([]Ban, error)
	ListBoards(ctx context.Context) ([]Board, error)
	ListReports(ctx context.Context, arg ListReportsParams) ([]ListReportsRow, error)
	ListThreadReplies(ctx context.Context, threadID string) ([]ListThreadRepliesRow, error)
	ReplyExists(ctx context.Context, arg ReplyExistsParams) (bool, error)
	RevokeFamily(ctx context.Context, familyID string) error
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	SetThreadLocked(ctx context.Context, arg SetThreadLockedParams) error
	SetThreadPinned(ctx context.Context, arg SetThreadPinnedParams) error
	TouchThreadBump(ctx context.Context, id string) error
	UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
	UserExistsByUsername(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
