// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, family_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, family_id, token_hash, revoked, replaced_by, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    string
	FamilyID  string
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.Revoked,
		&i.ReplacedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getActiveTokenByFamily = `-- name: GetActiveTokenByFamily :one
SELECT id, user_id, family_id, token_hash, revoked, replaced_by, expires_at, created_at
FROM refresh_tokens
WHERE family_id = $1 AND revoked = false
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveTokenByFamily(ctx context.Context, familyID string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getActiveTokenByFamily, familyID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.Revoked,
		&i.ReplacedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, family_id, token_hash, revoked, replaced_by, expires_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.Revoked,
		&i.ReplacedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeFamily = `-- name: RevokeFamily :exec
UPDATE refresh_tokens
SET revoked = true
WHERE family_id = $1
`

func (q *Queries) RevokeFamily(ctx context.Context, familyID string) error {
	_, err := q.db.Exec(ctx, revokeFamily, familyID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked = true, replaced_by = $2
WHERE id = $1
`

type RevokeRefreshTokenParams struct {
	ID         string
	ReplacedBy pgtype.UUID
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.ReplacedBy)
	return err
}
