// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replies.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReply = `-- name: CreateReply :one
INSERT INTO replies (thread_id, user_id, body, image_url, reply_to_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, thread_id, user_id, body, image_url, reply_to_id, created_at
`

type CreateReplyParams struct {
	ThreadID  string
	UserID    string
	Body      string
	ImageUrl  pgtype.Text
	ReplyToID pgtype.UUID
}

func (q *Queries) CreateReply(ctx context.Context, arg CreateReplyParams) (Reply, error) {
	row := q.db.QueryRow(ctx, createReply,
		arg.ThreadID,
		arg.UserID,
		arg.Body,
		arg.ImageUrl,
		arg.ReplyToID,
	)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.UserID,
		&i.Body,
		&i.ImageUrl,
		&i.ReplyToID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReply = `-- name: DeleteReply :exec
DELETE FROM replies WHERE id = $1
`

func (q *Queries) DeleteReply(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteReply, id)
	return err
}

const getReplyByID = `-- name: GetReplyByID :one
SELECT id, thread_id, user_id, body, image_url, reply_to_id, created_at
FROM replies
WHERE id = $1
`

func (q *Queries) GetReplyByID(ctx context.Context, id string) (Reply, error) {
	row := q.db.QueryRow(ctx, getReplyByID, id)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.UserID,
		&i.Body,
		&i.ImageUrl,
		&i.ReplyToID,
		&i.CreatedAt,
	)
	return i, err
}

const listThreadReplies = `-- name: ListThreadReplies :many
SELECT
    r.id,
    r.thread_id,
    r.user_id,
    r.body,
    r.image_url,
    r.reply_to_id,
    r.created_at,
    u.username AS author_name,
    u.role AS author_role
FROM replies r
JOIN users u ON u.id = r.user_id
WHERE r.thread_id = $1
ORDER BY r.created_at ASC
`

type ListThreadRepliesRow struct {
	ID         string
	ThreadID   string
	UserID     string
	Body       string
	ImageUrl   pgtype.Text
	ReplyToID  pgtype.UUID
	CreatedAt  time.Time
	AuthorName string
	AuthorRole string
}

func (q *Queries) ListThreadReplies(ctx context.Context, threadID string) ([]ListThreadRepliesRow, error) {
	rows, err := q.db.Query(ctx, listThreadReplies, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadRepliesRow
	for rows.Next() {
		var i ListThreadRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.UserID,
			&i.Body,
			&i.ImageUrl,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replyExists = `-- name: ReplyExists :one
SELECT EXISTS(SELECT 1 FROM replies WHERE id = $1 AND thread_id = $2)
`

type ReplyExistsParams struct {
	ID       string
	ThreadID string
}

func (q *Queries) ReplyExists(ctx context.Context, arg ReplyExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, replyExists, arg.ID, arg.ThreadID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
