// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (target_type, target_id, reporter_id, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, target_type, target_id, reporter_id, reason, status, created_at
`

type CreateReportParams struct {
	TargetType string
	TargetID   string
	ReporterID string
	Reason     string
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.TargetType,
		arg.TargetID,
		arg.ReporterID,
		arg.Reason,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.ReporterID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, target_type, target_id, reporter_id, reason, status, created_at
FROM reports
WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id string) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.ReporterID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT
    r.id,
    r.target_type,
    r.target_id,
    r.reporter_id,
    r.reason,
    r.status,
    r.created_at,
    u.username AS reporter_name,
    COALESCE((SELECT b.slug FROM threads t JOIN boards b ON b.id = t.board_id WHERE r.target_type = 'thread' AND t.id = r.target_id), '')::text AS target_board_slug,
    COALESCE((SELECT t.id FROM threads t WHERE r.target_type = 'thread' AND t.id = r.target_id), (SELECT t.id FROM replies rp JOIN threads t ON t.id = rp.thread_id WHERE r.target_type = 'reply' AND rp.id = r.target_id))::text AS target_thread_id,
    COALESCE((SELECT t.body FROM threads t WHERE r.target_type = 'thread' AND t.id = r.target_id), (SELECT rp.body FROM replies rp WHERE r.target_type = 'reply' AND rp.id = r.target_id))::text AS target_body
FROM reports r
JOIN users u ON u.id = r.reporter_id
WHERE r.status = $1
ORDER BY r.created_at ASC
LIMIT $2 OFFSET $3
`

type ListReportsParams struct {
	Status string
	Limit  int32
	Offset int32
}

type ListReportsRow struct {
	ID              string
	TargetType      string
	TargetID        string
	ReporterID      string
	Reason          string
	Status          string
	CreatedAt       time.Time
	ReporterName    string
	TargetBoardSlug string
	TargetThreadID  string
	TargetBody      string
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]ListReportsRow, error) {
	rows, err := q.db.Query(ctx, listReports, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsRow
	for rows.Next() {
		var i ListReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.ReporterID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.ReporterName,
			&i.TargetBoardSlug,
			&i.TargetThreadID,
			&i.TargetBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE reports SET status = $2 WHERE id = $1
RETURNING id, target_type, target_id, reporter_id, reason, status, created_at
`

type UpdateReportStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReportStatus, arg.ID, arg.Status)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.ReporterID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
