// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (slug, name, description)
VALUES ($1, $2, $3)
RETURNING id, slug, name, description, created_at
`

type CreateBoardParams struct {
	Slug        string
	Name        string
	Description string
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Slug, arg.Name, arg.Description)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO threads (board_id, user_id, title, body, image_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, board_id, user_id, title, body, image_url, is_pinned, is_locked, bumped_at, created_at
`

type CreateThreadParams struct {
	BoardID  string
	UserID   string
	Title    string
	Body     string
	ImageUrl pgtype.Text
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.BoardID,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.ImageUrl,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.ImageUrl,
		&i.IsPinned,
		&i.IsLocked,
		&i.BumpedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :exec
DELETE FROM threads WHERE id = $1
`

func (q *Queries) DeleteThread(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteThread, id)
	return err
}

const getBoardBySlug = `-- name: GetBoardBySlug :one
SELECT id, slug, name, description, created_at
FROM boards
WHERE slug = $1
`

func (q *Queries) GetBoardBySlug(ctx context.Context, slug string) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardBySlug, slug)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getBoardThreadCount = `-- name: GetBoardThreadCount :one
SELECT COUNT(*) FROM threads WHERE board_id = $1
`

func (q *Queries) GetBoardThreadCount(ctx context.Context, boardID string) (int64, error) {
	row := q.db.QueryRow(ctx, getBoardThreadCount, boardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBoardThreads = `-- name: GetBoardThreads :many
SELECT
    t.id,
    t.board_id,
    t.user_id,
    t.title,
    t.body,
    t.image_url,
    t.is_pinned,
    t.is_locked,
    t.bumped_at,
    t.created_at,
    b.slug AS board_slug,
    u.username AS author_name,
    u.role AS author_role,
    u.avatar_url AS author_avatar,
    rr.reply_count,
    rr.last_reply_at,
    (rr.last_reply_at IS NULL OR t.bumped_at >= rr.last_reply_at) AS bumped
FROM threads t
JOIN boards b ON b.id = t.board_id
JOIN users u ON u.id = t.user_id
LEFT JOIN LATERAL (
    SELECT COUNT(*) AS reply_count, COALESCE(MAX(r.created_at), t.created_at)::timestamptz AS last_reply_at
    FROM replies r
    WHERE r.thread_id = t.id
) rr ON true
WHERE t.board_id = $1 ORDER BY t.is_pinned DESC, t.bumped_at DESC
LIMIT $2 OFFSET $3
`

type GetBoardThreadsParams struct {
	BoardID string
	Limit   int32
	Offset  int32
}

type GetBoardThreadsRow struct {
	ID           string
	BoardID      string
	UserID       string
	Title        string
	Body         string
	ImageUrl     pgtype.Text
	IsPinned     bool
	IsLocked     bool
	BumpedAt     time.Time
	CreatedAt    time.Time
	BoardSlug    string
	AuthorName   string
	AuthorRole   string
	AuthorAvatar pgtype.Text
	ReplyCount   int64
	LastReplyAt  time.Time
	Bumped       pgtype.Bool
}

func (q *Queries) GetBoardThreads(ctx context.Context, arg GetBoardThreadsParams) ([]GetBoardThreadsRow, error) {
	rows, err := q.db.Query(ctx, getBoardThreads, arg.BoardID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBoardThreadsRow
	for rows.Next() {
		var i GetBoardThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.ImageUrl,
			&i.IsPinned,
			&i.IsLocked,
			&i.BumpedAt,
			&i.CreatedAt,
			&i.BoardSlug,
			&i.AuthorName,
			&i.AuthorRole,
			&i.AuthorAvatar,
			&i.ReplyCount,
			&i.LastReplyAt,
			&i.Bumped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreadBoardID = `-- name: GetThreadBoardID :one
SELECT board_id FROM threads WHERE id = $1
`

func (q *Queries) GetThreadBoardID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getThreadBoardID, id)
	var board_id string
	err := row.Scan(&board_id)
	return board_id, err
}

const getThreadByID = `-- name: GetThreadByID :one
SELECT
    t.id,
    t.board_id,
    t.user_id,
    t.title,
    t.body,
    t.image_url,
    t.is_pinned,
    t.is_locked,
    t.bumped_at,
    t.created_at,
    b.slug AS board_slug,
    u.username AS author_name,
    u.role AS author_role,
    u.avatar_url AS author_avatar,
    rr.reply_count,
    rr.last_reply_at,
    (rr.last_reply_at IS NULL OR t.bumped_at >= rr.last_reply_at) AS bumped
FROM threads t
JOIN boards b ON b.id = t.board_id
JOIN users u ON u.id = t.user_id
LEFT JOIN LATERAL (
    SELECT COUNT(*) AS reply_count, COALESCE(MAX(r.created_at), t.created_at)::timestamptz AS last_reply_at
    FROM replies r
    WHERE r.thread_id = t.id
) rr ON true
WHERE t.id = $1
`

type GetThreadByIDRow struct {
	ID           string
	BoardID      string
	UserID       string
	Title        string
	Body         string
	ImageUrl     pgtype.Text
	IsPinned     bool
	IsLocked     bool
	BumpedAt     time.Time
	CreatedAt    time.Time
	BoardSlug    string
	AuthorName   string
	AuthorRole   string
	AuthorAvatar pgtype.Text
	ReplyCount   int64
	LastReplyAt  time.Time
	Bumped       pgtype.Bool
}

func (q *Queries) GetThreadByID(ctx context.Context, id string) (GetThreadByIDRow, error) {
	row := q.db.QueryRow(ctx, getThreadByID, id)
	var i GetThreadByIDRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.ImageUrl,
		&i.IsPinned,
		&i.IsLocked,
		&i.BumpedAt,
		&i.CreatedAt,
		&i.BoardSlug,
		&i.AuthorName,
		&i.AuthorRole,
		&i.AuthorAvatar,
		&i.ReplyCount,
		&i.LastReplyAt,
		&i.Bumped,
	)
	return i, err
}

const listBoards = `-- name: ListBoards :many
SELECT id, slug, name, description, created_at
FROM boards
ORDER BY created_at ASC
`

func (q *Queries) ListBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setThreadLocked = `-- name: SetThreadLocked :exec
UPDATE threads SET is_locked = $2 WHERE id = $1
`

type SetThreadLockedParams struct {
	ID       string
	IsLocked bool
}

func (q *Queries) SetThreadLocked(ctx context.Context, arg SetThreadLockedParams) error {
	_, err := q.db.Exec(ctx, setThreadLocked, arg.ID, arg.IsLocked)
	return err
}

const setThreadPinned = `-- name: SetThreadPinned :exec
UPDATE threads SET is_pinned = $2 WHERE id = $1
`

type SetThreadPinnedParams struct {
	ID       string
	IsPinned bool
}

func (q *Queries) SetThreadPinned(ctx context.Context, arg SetThreadPinnedParams) error {
	_, err := q.db.Exec(ctx, setThreadPinned, arg.ID, arg.IsPinned)
	return err
}

const touchThreadBump = `-- name: TouchThreadBump :exec
UPDATE threads SET bumped_at = now()
WHERE id = $1
`

func (q *Queries) TouchThreadBump(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchThreadBump, id)
	return err
}
