// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, avatar_url, bio, role, color)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, email, password_hash, avatar_url, bio, role, color, created_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	AvatarUrl    pgtype.Text
	Bio          string
	Role         string
	Color        string
}

type CreateUserRow struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	AvatarUrl    pgtype.Text
	Bio          string
	Role         string
	Color        string
	CreatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.AvatarUrl,
		arg.Bio,
		arg.Role,
		arg.Color,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, avatar_url, bio, role, color, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	AvatarUrl    pgtype.Text
	Bio          string
	Role         string
	Color        string
	CreatedAt    time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, avatar_url, bio, role, color, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	AvatarUrl    pgtype.Text
	Bio          string
	Role         string
	Color        string
	CreatedAt    time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, avatar_url, bio, role, color, created_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	AvatarUrl    pgtype.Text
	Bio          string
	Role         string
	Color        string
	CreatedAt    time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPublicByUsername = `-- name: GetUserPublicByUsername :one
SELECT id, username, avatar_url, bio, role, color, created_at
FROM users
WHERE username = $1
`

type GetUserPublicByUsernameRow struct {
	ID        string
	Username  string
	AvatarUrl pgtype.Text
	Bio       string
	Role      string
	Color     string
	CreatedAt time.Time
}

func (q *Queries) GetUserPublicByUsername(ctx context.Context, username string) (GetUserPublicByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserPublicByUsername, username)
	var i GetUserPublicByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET avatar_url = CASE WHEN $2::text = '' THEN avatar_url ELSE $2::text END,
    bio = CASE WHEN $3::text = '' THEN bio ELSE $3::text END,
    color = CASE WHEN $4::text = '' THEN color ELSE $4::text END
WHERE id = $1
RETURNING id, username, email, password_hash, avatar_url, bio, role, color, created_at
`

type UpdateUserProfileParams struct {
	ID      string
	Column2 string
	Column3 string
	Column4 string
}

type UpdateUserProfileRow struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	AvatarUrl    pgtype.Text
	Bio          string
	Role         string
	Color        string
	CreatedAt    time.Time
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByUsername = `-- name: UserExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UserExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
